image: Visual Studio 2017
skip_tags: true
branches:
  only:
    - master
build_script:
  - nuget restore Installer.sln
  - msbuild Installer.sln /p:Configuration=Release;Version=$(appveyor_build_version)
  - ps: rm Installer/bin/Release/*.pdb
  - ps: Invoke-WebRequest -Uri "https://github.com/dgiagio/warp/releases/download/v0.3.0/windows-x64.warp-packer.exe" -OutFile warp-packer.exe
  - ps: .\warp-packer.exe --arch windows-x64 --input_dir Installer/bin/Release --exec Installer.exe --output Installer.exe
  - '\"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\editbin.exe\" /subsystem:windows Installer.exe'
artifacts:
  - path: Installer.exe
    name: Installer
deploy:
  release: v$(appveyor_build_version)
  description: 'Release'
  provider: GitHub
  auth_token: $(github_release_token)
  artifact: Installer
  draft: false
  prerelease: false